-- MySQL Script generated by MySQL Workbench
-- Fri May 27 23:56:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cd&dvd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cd&dvd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cd&dvd` DEFAULT CHARACTER SET utf8 ;
USE `cd&dvd` ;

-- -----------------------------------------------------
-- Table `cd&dvd`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`author` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`album` (
  `name` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL,
  `author_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_album_author1_idx` (`author_name` ASC) VISIBLE,
  CONSTRAINT `fk_album_author1`
    FOREIGN KEY (`author_name`)
    REFERENCES `cd&dvd`.`author` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`music` (
  `name` VARCHAR(255) NOT NULL,
  `album_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_music_album_idx` (`album_name` ASC) VISIBLE,
  CONSTRAINT `fk_music_album`
    FOREIGN KEY (`album_name`)
    REFERENCES `cd&dvd`.`album` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`producer` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`movie` (
  `name` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `producer_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_movie_producer1_idx` (`producer_name` ASC) VISIBLE,
  CONSTRAINT `fk_movie_producer1`
    FOREIGN KEY (`producer_name`)
    REFERENCES `cd&dvd`.`producer` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`actor` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cd&dvd`.`actor_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cd&dvd`.`actor_has_movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actor_name` VARCHAR(255) NOT NULL,
  `movie_name` VARCHAR(255) NOT NULL,
  INDEX `fk_actor_has_movie_movie1_idx` (`movie_name` ASC) VISIBLE,
  INDEX `fk_actor_has_movie_actor1_idx` (`actor_name` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_actor_has_movie_actor1`
    FOREIGN KEY (`actor_name`)
    REFERENCES `cd&dvd`.`actor` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_has_movie_movie1`
    FOREIGN KEY (`movie_name`)
    REFERENCES `cd&dvd`.`movie` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
